### ISSUE TITLE
extended attributes discarded for layered changes

### ISSUE THREAD

**Issue by cgwalters** [ostreedev/ostree-rs-ext#654]
Right now when we filter the tar stream we end up discarding xattrs - there's a bit of nontrivial work necessary on our side to handle this.

It also opens up the interesting question of whether we try to e.g. honor any `security.selinux` that may be present.

It is clear that we definitely want `security.capability`, and for that matter we might as well propagate things like `user.`.

**Comment by antheas** [comment]
Here is a workaround required due to this at the moment. Since bazzite is using rechunk this can be removed, but it is used throughout Universal Blue images and derivatives. For other applications as well.

https://github.com/ublue-os/bazzite/blob/9a9a4861b025f44aaf6cd40ff006c911fa3abe01/system_files/desktop/shared/usr/lib/systemd/system/gamescope-workaround.service

This also has the side effect of corrupting the OSTree file hashes, and might be partially behind https://github.com/secureblue/secureblue/issues/369 which fails when setting xattrs.

**Comment by ggiguash** [comment]
@cgwalters , the [mentioned workaround](https://github.com/ublue-os/bazzite/blob/9a9a4861b025f44aaf6cd40ff006c911fa3abe01/system_files/desktop/shared/usr/lib/systemd/system/gamescope-workaround.service) is for an executable on the host file system.

If we know that we "lost" a capability in an executable inside a given image, is there a hacky way to set it?

**Comment by cgwalters** [comment]
There's no real build-time workaround for this - short of going to the level of editing the tarballs output from a build.

**Comment by vrothberg** [comment]
@cgwalters, do we other options than rechunking?  IDM is blocked on this issue, so I am trying to educate myself a bit more in this problem space.

**Comment by antheas** [comment]
Hi Valentin, as a dirty workaround something like the service I posted above works and was used for months in Universal Blue for multiple projects

**Comment by vrothberg** [comment]
Thanks for sharing, @antheas !

**Comment by abbra** [comment]
We are planning to move some of FreeIPA rpm post-install scripts into a separate service we can run on each reboot, so the approach to add capabilities through the hack is something that we might consider as well.  However, for IdM customers modification of the immutable parts of the image at instantiation time would be unacceptable.

**Comment by cgwalters** [comment]
This is fixed as part of https://github.com/ostreedev/ostree-rs-ext/pull/679
